name: fin_glow
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.19
  flutter_native_splash: ^2.4.1
  convex_bottom_bar: ^3.0.0
  image_picker: ^0.8.4+7
  icons_plus: ^5.0.0 
  fl_chart: ^0.68.0
  logger: ^2.4.0 
  carousel_slider: ^4.2.1
  shared_preferences: ^2.3.1
  intl: ^0.19.0
  money_formatter: ^0.0.6
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_app.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/styles/Montserrat.ttf
    - family: Raleway
      fonts:
        - asset: assets/styles/Raleway.ttf
  assets:
    - assets/images/logo_vertical.png
    - assets/images/APPSPLASH.mp4
    - assets/images/deposit_icon.png
    - assets/images/transfer_icon.png
    - assets/images/icon_app.png
    - assets/images/clabe_icon.png
    - assets/images/card_basic.png
    - assets/images/card_gold.png
    - assets/images/virtual_card_basic.png
    - assets/json/movements.json
    - assets/images/key_icon.png
    - assets/images/power_icon.png
    - assets/images/gear_icon.png
    - assets/images/image_publicidad.png
    - assets/images/image_publicidad2.png
    - assets/images/image_publicidad3.png
    - assets/json/cash_data.json
    - assets/json/weekly_data.json
    - assets/json/store_data.json
    - assets/json/seminary_data.json
    - assets/json/financial_advisor_data.json
    - assets/json/profile_data.json